var Connecticut =[
  'Bridgeport, CT'
,'Stamford, CT'
,'New Haven, CT'
,'Hartford, CT'
,'Waterbury, CT'
,'Norwalk, CT'
,'Danbury, CT'
,'New Britain, CT'
,'West Hartford, CT'
,'Greenwich, CT'
,'Fairfield, CT'
,'Hamden, CT'
,'Meriden, CT'
,'Bristol, CT'
,'Manchester, CT'
,'West Haven, CT'
,'Stratford, CT'
,'Milford, CT'
,'East Hartford, CT'
,'Middletown, CT'
,'Wallingford, CT'
,'Southington, CT'
,'Enfield, CT'
,'Shelton, CT'
,'Norwich, CT'
,'Groton, CT'
,'Trumbull, CT'
,'Torrington, CT'
,'Glastonbury, CT'
,'Naugatuck, CT'
,'Newington, CT'
,'Vernon, CT'
,'Windsor, CT'
,'Cheshire, CT'
,'Branford, CT'
,'New Milford, CT'
,'East Haven, CT'
,'New London, CT'
,'Wethersfield, CT'
,'Newtown, CT'
,'Westport, CT'
,'South Windsor, CT'
,'Farmington, CT'
,'Mansfield, CT'
,'Ridgefield, CT'
,'Simsbury, CT'
,'Windham, CT'
,'North Haven, CT'
,'Watertown, CT'
,'Guilford, CT'
,'Bloomfield, CT'
,'Darien, CT'
,'Rocky Hill, CT'
,'New Canaan, CT'
,'Bethel, CT'
,'Berlin, CT'
,'Southbury, CT'
,'Waterford, CT'
,'Avon, CT'
,'Ansonia, CT'
,'Monroe, CT'
,'East Lyme, CT'
,'Wilton, CT'
,'Montville, CT'
,'Stonington, CT'
,'Killingly, CT'
,'Madison, CT'
,'Brookfield, CT'
,'Plainville, CT'
,'Seymour, CT'
,'Ellington, CT'
,'Wolcott, CT'
,'Suffield, CT'
,'Colchester, CT'
,'Ledyard, CT'
,'Plainfield, CT'
,'Tolland, CT'
,'Orange, CT'
,'Cromwell, CT'
,'New Fairfield, CT'
,'North Branford, CT'
,'Clinton, CT'
,'East Hampton, CT'
,'Oxford, CT'
,'Windsor Locks, CT'
,'Derby, CT'
,'Coventry, CT'
,'Plymouth, CT'
,'Stafford, CT'
,'Griswold, CT'
,'East Windsor, CT'
,'Granby, CT'
,'Old Saybrook, CT'
,'Weston, CT'
,'Somers, CT'
,'Winchester, CT'
,'Canton, CT'
];
