var Maryland = [
  'Baltimore, MD'
,'Columbia, MD'
,'Germantown, MD'
,'Waldorf, MD'
,'Silver Spring, MD'
,'Frederick, MD'
,'Ellicott City, MD'
,'Glen Burnie, MD'
,'Gaithersburg, MD'
,'Bethesda, MD'
,'Dundalk, MD'
,'Rockville, MD'
,'Towson, MD'
,'Bowie, MD'
,'Bel Air South, MD'
,'Severn, MD'
,'Wheaton, MD'
,'Aspen Hill, MD'
,'North Bethesda, MD'
,'Potomac, MD'
,'Catonsville, MD'
,'Hagerstown, MD'
,'Odenton, MD'
,'Annapolis, MD'
,'Essex, MD'
,'Woodlawn, MD'
,'Severna Park, MD'
,'Clinton, MD'
,'Chillum, MD'
,'Olney, MD'
,'Owings Mills, MD'
,'Montgomery Village, MD'
,'College Park, MD'
,'Pikesville, MD'
,'Randallstown, MD'
,'Middle River, MD'
,'Salisbury, MD'
,'Pasadena, MD'
,'Eldersburg, MD'
,'Bel Air North, MD'
,'Parkville, MD'
,'Milford Mill, MD'
,'Laurel, MD'
,'Crofton, MD'
,'South Laurel, MD'
,'Perry Hall, MD'
,'Carney, MD'
,'Clarksburg, MD'
,'Ilchester, MD'
,'Reisterstown, MD'
,'Landover, MD'
,'Suitland, MD'
,'Edgewood, MD'
,'Lochearn, MD'
,'Fairland, MD'
,'North Laurel, MD'
,'Elkridge, MD'
,'Ballenger Creek, MD'
,'Greenbelt, MD'
,'Fort Washington, MD'
,'Cockeysville, MD'
,'Arnold, MD'
,'North Potomac, MD'
,'Camp Springs, MD'
,'Arbutus, MD'
,'Hyattsville, MD'
,'Beltsville, MD'
,'Langley Park and Westminster, MD'
,'Rosedale, MD'
,'Seabrook, MD'
,'Lake Shore, MD'
,'Maryland City, MD'
,'Cumberland, MD'
,'Oxon Hill, MD'
,'Redland, MD'
,'East Riverdale, MD'
,'Glassmanor, MD'
,'Parole, MD'
,'Takoma Park, MD'
,'Calverton, MD'
,'Damascus, MD'
,'Easton, MD'
,'Ferndale, MD'
,'Adelphi, MD'
,'Glenmont, MD'
,'White Oak, MD'
,'Aberdeen, MD'
,'Brooklyn Park, MD'
,'Rossville, MD'
,'Elkton, MD'
,'Hillcrest Heights, MD'
,'Colesville, MD'
,'Bensville, MD'
,'Cloverly, MD'
,'Havre de Grace, MD'
,'Summerfield, MD'
,'Glenn Dale, MD'
,'Lake Arbor, MD'
,'Kettering, MD'
,'Accokeek, MD'
,'New Carrollton, MD'
,'Joppatowne, MD'
,'Kemp Mill, MD'
,'Lexington Park, MD'
,'Urbana, MD'
,'Brock Hall, MD'
,'Cambridge, MD'
,'California, MD'
,'Overlea, MD'
,'Forestville, MD'
,'Riviera Beach, MD'
,'Linganore, MD'
,'Mays Chapel, MD'
,'Walker Mill, MD'
,'Ocean Pines, MD'
,'Travilah, MD'
,'Halfway, MD'
,'Westphalia, MD'
,'Largo, MD'
,'Rosaryville, MD'
,'Lanham, MD'
,'Linthicum, MD'
,'Mitchellville, MD'
,'Annapolis Neck, MD'
,'Bel Air town, MD'
,'Brandywine, MD'
,'Jessup, MD'
,'Timonium, MD'
,'Chesapeake Ranch Estates, MD'
,'White Marsh, MD'
,'Chevy Chase CDP, MD'
,'La Plata, MD'
];
