var Massachusetts = [
  'Boston, MA'
,'Worcester, MA'
,'Springfield, MA'
,'Cambridge, MA'
,'Lowell, MA'
,'Brockton, MA'
,'Quincy, MA'
,'Lynn, MA'
,'New Bedford, MA'
,'Fall River, MA'
,'Lawrence, MA'
,'Newton, MA'
,'Somerville, MA'
,'Framingham, MA'
,'Haverhill, MA'
,'Malden, MA'
,'Waltham, MA'
,'Brookline, MA'
,'Revere, MA'
,'Plymouth, MA'
,'Medford, MA'
,'Taunton, MA'
,'Weymouth Town, MA'
,'Chicopee, MA'
,'Peabody, MA'
,'Methuen Town, MA'
,'Everett, MA'
,'Barnstable Town, MA'
,'Attleboro, MA'
,'Arlington, MA'
,'Salem, MA'
,'Pittsfield, MA'
,'Leominster, MA'
,'Beverly, MA'
,'Billerica, MA'
,'Fitchburg, MA'
,'Marlborough, MA'
,'Woburn, MA'
,'Westfield, MA'
,'Chelsea, MA'
,'Amherst, MA'
,'Braintree Town, MA'
,'Shrewsbury, MA'
,'Holyoke, MA'
,'Natick, MA'
,'Andover, MA'
,'Chelmsford, MA'
,'Watertown Town, MA'
,'Randolph Town, MA'
,'Lexington, MA'
,'Dartmouth, MA'
,'Franklin Town, MA'
,'Dracut, MA'
,'Falmouth, MA'
,'Needham, MA'
,'Norwood, MA'
,'Tewksbury, MA'
,'North Andover, MA'
,'Milford, MA'
,'Melrose, MA'
,'Gloucester, MA'
,'Northampton, MA'
,'Wellesley, MA'
,'Stoughton, MA'
,'North Attleborough, MA'
,'West Springfield Town, MA'
,'Agawam Town, MA'
,'Bridgewater Town, MA'
,'Milton, MA'
,'Saugus, MA'
,'Danvers, MA'
,'Belmont, MA'
,'Wakefield, MA'
,'Walpole, MA'
,'Burlington, MA'
,'Marshfield, MA'
,'Reading, MA'
,'Dedham, MA'
,'Easton, MA'
,'Yarmouth, MA'
,'Westford, MA'
,'Canton, MA'
,'Hingham, MA'
,'Middleborough, MA'
,'Acton, MA'
,'Mansfield, MA'
,'Wilmington, MA'
,'Wareham, MA'
,'Stoneham, MA'
,'Winchester, MA'
,'Westborough, MA'
,'Gardner, MA'
,'Ludlow, MA'
,'Bourne, MA'
,'Marblehead, MA'
,'Sandwich, MA'
,'Hudson, MA'
,'Holden, MA'
,'Grafton, MA'
,'Winthrop Town, MA'
,'Norton, MA'
,'Scituate, MA'
,'Sudbury, MA'
,'Ashland, MA'
,'Hopkinton, MA'
,'Foxborough, MA'
,'Sharon, MA'
,'Concord, MA'
,'Pembroke, MA'
,'Somerset, MA'
,'Newburyport, MA'
,'South Hadley, MA'
,'Rockland, MA'
,'Webster, MA'
,'Southbridge Town, MA'
,'Greenfield Town, MA'
,'Amesbury Town, MA'
,'Swansea, MA'
,'Abington, MA'
,'Bellingham, MA'
,'Auburn, MA'
,'East Longmeadow, MA'
,'Westport, MA'
,'Northbridge, MA'
,'Westwood, MA'
,'Easthampton Town, MA'
,'Duxbury, MA'
,'Fairhaven, MA'
,'Longmeadow, MA'
,'Northborough, MA'
,'North Reading, MA'
,'Seekonk, MA'
,'Clinton, MA'
,'Belchertown, MA'
,'Raynham, MA'
,'Whitman, MA'
,'Swampscott, MA'
,'Mashpee, MA'
,'Holliston, MA'
,'Hanover, MA'
,'Dennis, MA'
,'Wilbraham, MA'
,'East Bridgewater, MA'
,'Bedford, MA'
,'Nantucket, MA'
,'Uxbridge, MA'
,'Wayland, MA'
,'Millbury, MA'
,'Ipswich, MA'
,'Kingston, MA'
,'Harwich, MA'
,'Oxford, MA'
,'Charlton, MA'
,'Medway, MA'
,'Lynnfield, MA'
,'North Adams, MA'
,'Medfield, MA'
,'Rehoboth, MA'
,'Palmer Town, MA'
,'Tyngsborough, MA'
,'Wrentham, MA'
,'Spencer, MA'
,'Athol, MA'
,'Dudley, MA'
,'Weston, MA'
,'Lunenburg, MA'
,'Norfolk, MA'
,'Carver, MA'
,'Pepperell, MA'
,'Lakeville, MA'
,'Holbrook, MA'
,'Norwell, MA'
,'Groton, MA'
,'Leicester, MA'
,'Maynard, MA'
,'Hanson, MA'
,'Acushnet, MA'
,'Southborough, MA'
,'Winchendon, MA'
,'Brewster, MA'
,'Littleton, MA'
,'Hull, MA'
,'Ware, MA'
];
