var Minnesota = [
  'Minneapolis, MN'
,'St. Paul, MN'
,'Rochester, MN'
,'Bloomington, MN'
,'Duluth, MN'
,'Brooklyn Park, MN'
,'Plymouth, MN'
,'Woodbury, MN'
,'Maple Grove, MN'
,'Blaine, MN'
,'Lakeville, MN'
,'St. Cloud, MN'
,'Eagan, MN'
,'Burnsville, MN'
,'Eden Prairie, MN'
,'Coon Rapids, MN'
,'Apple Valley, MN'
,'Minnetonka, MN'
,'Edina, MN'
,'St. Louis Park, MN'
,'Moorhead, MN'
,'Mankato, MN'
,'Shakopee, MN'
,'Maplewood, MN'
,'Cottage Grove, MN'
,'Richfield, MN'
,'Roseville, MN'
,'Inver Grove Heights, MN'
,'Brooklyn Center, MN'
,'Andover, MN'
,'Savage, MN'
,'Fridley, MN'
,'Oakdale, MN'
,'Chaska, MN'
,'Ramsey, MN'
,'Prior Lake, MN'
,'Shoreview, MN'
,'Owatonna, MN'
,'Austin, MN'
,'Winona, MN'
,'Chanhassen, MN'
,'Elk River, MN'
,'Rosemount, MN'
,'White Bear Lake, MN'
,'Faribault, MN'
,'Champlin, MN'
,'Farmington, MN'
,'New Brighton, MN'
,'Crystal, MN'
,'Golden Valley, MN'
,'Hastings, MN'
,'New Hope, MN'
,'Columbia Heights, MN'
,'Lino Lakes, MN'
,'Willmar, MN'
,'Northfield, MN'
,'South St. Paul, MN'
,'West St. Paul, MN'
,'Forest Lake, MN'
,'Otsego, MN'
,'Stillwater, MN'
,'Sartell, MN'
,'Hopkins, MN'
,'Albert Lea, MN'
,'St. Michael, MN'
,'Anoka, MN'
,'Red Wing, MN'
,'Ham Lake, MN'
,'Hibbing, MN'
,'Buffalo, MN'
,'Hugo, MN'
,'Robbinsdale, MN'
,'Hutchinson, MN'
,'Bemidji, MN'
,'Monticello, MN'
,'Brainerd, MN'
,'Alexandria, MN'
,'North Mankato, MN'
,'New Ulm, MN'
,'Fergus Falls, MN'
,'Worthington, MN'
,'Sauk Rapids, MN'
,'Marshall, MN'
,'Rogers, MN'
,'Mounds View, MN'
,'Waconia, MN'
,'Vadnais Heights, MN'
,'Cloquet, MN'
,'North St. Paul, MN'
,'St. Peter, MN'
,'East Bethel, MN'
,'Mendota Heights, MN'
,'Big Lake city, MN'
,'Lake Elmo, MN'
,'Grand Rapids, MN'
,'Little Canada, MN'
,'North Branch, MN'
,'Victoria, MN'
,'Fairmont, MN'
,'Hermantown, MN'
];
