var Wisconsin = [
  'Milwaukee, WI'
,'Madison, WI'
,'Green Bay, WI'
,'Kenosha, WI'
,'Racine, WI'
,'Appleton, WI'
,'Waukesha, WI'
,'Eau Claire, WI'
,'Oshkosh, WI'
,'Janesville, WI'
,'West Allis, WI'
,'La Crosse, WI'
,'Sheboygan, WI'
,'Wauwatosa, WI'
,'Fond du Lac, WI'
,'Brookfield, WI'
,'New Berlin, WI'
,'Wausau, WI'
,'Menomonee Falls, WI'
,'Greenfield, WI'
,'Franklin, WI'
,'Beloit, WI'
,'Oak Creek, WI'
,'Sun Prairie, WI'
,'Manitowoc, WI'
,'West Bend, WI'
,'Fitchburg, WI'
,'Mount Pleasant, WI'
,'Neenah, WI'
,'Superior, WI'
,'Stevens Point, WI'
,'De Pere, WI'
,'Caledonia, WI'
,'Mequon, WI'
,'Muskego, WI'
,'Watertown, WI'
,'Middleton, WI'
,'Pleasant Prairie, WI'
,'Germantown, WI'
,'South Milwaukee, WI'
,'Howard, WI'
,'Fox Crossing, WI'
,'Marshfield, WI'
,'Wisconsin Rapids, WI'
,'Onalaska, WI'
,'Menasha, WI'
,'Cudahy, WI'
,'Oconomowoc, WI'
,'Kaukauna, WI'
,'Ashwaubenon, WI'
,'Menomonie, WI'
,'Beaver Dam, WI'
,'River Falls, WI'
,'Bellevue, WI'
,'Pewaukee, WI'
,'Weston, WI'
,'Hartford, WI'
,'Whitefish Bay, WI'
,'Whitewater, WI'
,'Waunakee, WI'
,'Greendale, WI'
,'Hudson, WI'
,'Chippewa Falls, WI'
,'Salem Lakes, WI'
,'Allouez, WI'
,'Verona, WI'
,'Shorewood, WI'
,'Plover, WI'
,'Glendale, WI'
,'Stoughton, WI'
,'Suamico, WI'
,'Fort Atkinson, WI'
,'Baraboo, WI'
,'Brown Deer, WI'
,'Harrison, WI'
,'Port Washington, WI'
,'Cedarburg, WI'
,'Grafton, WI'
,'Platteville, WI'
,'Richfield, WI'
,'Little Chute, WI'
,'Sussex, WI'
,'Waupun, WI'
,'Two Rivers, WI'
,'Oregon, WI'
,'Marinette, WI'
,'Burlington, WI'
,'DeForest, WI'
,'Holmen and Monroe, WI'
,'Portage, WI'
,'Elkhorn, WI'
,'Hobart, WI'
,'New Richmond, WI'
,'Sparta, WI'
];
